# Generated by Django 4.1.7 on 2023-03-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(editable=False, max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre corto'),
        ),
    ]
